[package]
name = "puppyarm"
version = "0.1.0"
edition = "2024"

[dependencies]
pge = { path = "../../", features = ["wgpu_winit"] }

[features]
default = ["wgpu_winit"]
wgpu_winit = ["pge/wgpu_winit"]
